# Generated by Django 5.2.1 on 2025-06-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.options'),
            preserve_default=False,
        ),
    ]
