# Generated by Django 5.2.1 on 2025-06-13 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='student',
        ),
        migrations.AddField(
            model_name='projects',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
