# Generated by Django 5.2.1 on 2025-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_name_options_name_remove_projects_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
