# Generated by Django 5.2.1 on 2025-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_reports_hourse_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='hourse_worked',
            field=models.CharField(max_length=2),
        ),
    ]
