# Generated by Django 5.2.1 on 2025-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_reports_hourse_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='hourse_worked',
            field=models.FloatField(default=0.0),
        ),
    ]
