# Generated by Django 3.2.19 on 2025-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_reports_hourse_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prifile_picture',
            field=models.ImageField(default=1, upload_to='user/'),
            preserve_default=False,
        ),
    ]
