# Generated by Django 3.2.19 on 2025-07-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_prifile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prifile_picture',
            new_name='profile_picture',
        ),
    ]
