# Generated by Django 3.2.19 on 2025-07-20 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20250710_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='base.option', unique=True),
            preserve_default=False,
        ),
    ]
