# Generated by Django 3.2.19 on 2025-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_studentprofile_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='670000000', max_length=20),
        ),
    ]
