# Generated by Django 3.2.19 on 2025-07-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='base.option'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='base.user'),
        ),
    ]
