# Generated by Django 3.2.19 on 2025-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20250720_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'student'}, related_name='tasks', to='base.User'),
        ),
    ]
