# Generated by Django 3.2.19 on 2025-07-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20250721_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
    ]
