# Generated by Django 3.2.19 on 2025-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20250721_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'student'}, related_name='projects', to='base.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'student'}, related_name='tasks', to='base.User'),
        ),
    ]
