# Generated by Django 3.2.19 on 2025-07-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20250721_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(related_name='tasks', to='base.StudentProfile'),
        ),
    ]
