# Generated by Django 3.2.19 on 2025-07-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_task_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.mentorprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.mentorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='base.StudentProfile'),
        ),
    ]
