# Generated by Django 3.2.19 on 2025-07-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20250721_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
