# Generated by Django 3.2.19 on 2025-07-25 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_report_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('tech_field', models.CharField(max_length=100, verbose_name='Tech Field')),
                ('thumbnail', models.URLField(verbose_name='Thumbnail URL')),
                ('video_id', models.CharField(max_length=100, verbose_name='Video ID')),
                ('duration', models.CharField(max_length=20, verbose_name='Duration')),
                ('views', models.CharField(max_length=50, verbose_name='Views')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('instructor', models.CharField(max_length=255, verbose_name='Instructor')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmojiReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('🔥', 'Fire'), ('😮', 'Surprised'), ('💡', 'Insightful')], max_length=5, verbose_name='Emoji')),
                ('reacted_on', models.DateTimeField(auto_now_add=True, verbose_name='Reacted On')),
            ],
            options={
                'verbose_name': 'Emoji Reaction',
                'verbose_name_plural': 'Emoji Reactions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('reacted', models.BooleanField(default=False, verbose_name='Reacted')),
                ('assigned_date', models.DateTimeField(verbose_name='Assigned Date')),
            ],
            options={
                'verbose_name': 'Student Course Progress',
                'verbose_name_plural': 'Student Course Progress',
            },
        ),
        migrations.AlterModelOptions(
            name='mentorprofile',
            options={'verbose_name': 'Mentor Profile', 'verbose_name_plural': 'Mentor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['name'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Expertise'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='base.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='base.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Option Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.mentorprofile', verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='base.StudentProfile', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hours_worked',
            field=models.FloatField(default=0.0, verbose_name='Hours Worked'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='report',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base.user', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.CharField(max_length=100, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='base.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='base.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='base.mentorprofile', verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='base.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(related_name='tasks', to='base.StudentProfile', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='670000000', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=500, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor')], default='student', max_length=10, verbose_name='User Type'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('user', 'option')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['option'], name='base_projec_option__2db3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['due_date'], name='base_projec_due_dat_280ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['student'], name='base_report_student_408ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['option'], name='base_report_option__0bcc07_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='base_report_status_c5cafe_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created'], name='base_report_created_dcb864_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['option'], name='base_task_option__75e704_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='base_task_due_dat_8d0cee_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='base_user_user_ty_ea6820_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='base_user_last_na_3a66a6_idx'),
        ),
        migrations.AddField(
            model_name='studentcourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='base.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='studentcourseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='base.studentprofile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='emojireaction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='base.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='emojireaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='base.studentprofile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base.option', verbose_name='Option'),
        ),
        migrations.AddIndex(
            model_name='studentcourseprogress',
            index=models.Index(fields=['student'], name='base_studen_student_b53e59_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseprogress',
            index=models.Index(fields=['course'], name='base_studen_course__a6ed81_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseprogress',
            index=models.Index(fields=['completed'], name='base_studen_complet_51b0dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseprogress',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='base_notifi_user_id_ec80cb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='base_notifi_is_read_d15f75_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='base_notifi_created_81a211_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['student'], name='base_emojir_student_f4a1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='emojireaction',
            index=models.Index(fields=['course'], name='base_emojir_course__77ffcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emojireaction',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['option'], name='base_course_option__4b7985_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tech_field'], name='base_course_tech_fi_2548df_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['order'], name='base_course_order_d70e3d_idx'),
        ),
    ]
